# -*- coding: utf-8 -*-
"""main_simulation.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QRGo-S1xl95epbrM-j_HR05-Vdpvgt8T
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Signal Configuration (6G Sub-THz Spectrum Simulation)
# Note: Using a relative scale for Sub-THz frequencies (Initial 6G Band)
frequency = 100e9      # 100 GHz (Early 6G spectrum)
sampling_rate = 1e12
time = np.linspace(0, 50e-11, 1000) # Pico-second time scale

# 2. Carrier Wave Generation
signal = np.sin(2 * np.pi * frequency * time)

# 3. Signal Propagation & Path Loss Simulation
# 6G signals suffer from high atmospheric attenuation; modeled here using an exponential decay filter
distance_factor = np.exp(-time * 1e10)
attenuated_signal = signal * distance_factor

# 4. Signal Visualization
plt.figure(figsize=(12, 6))

# Plot 1: Pristine 6G Carrier Signal
plt.subplot(2, 1, 1)
plt.plot(time, signal, color='blue')
plt.title("6G Signal Pattern (100 GHz Sub-THz)")
plt.ylabel("Amplitude")
plt.grid(True)

# Plot 2: Signal Attenuation Analysis (Impact of Distance/Obstacles)
plt.subplot(2, 1, 2)
plt.plot(time, attenuated_signal, color='red')
plt.title("6G Signal Attenuation (Path Loss & Atmospheric Fading)")
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude")
plt.grid(True)

plt.tight_layout()
plt.show()

# 1. Advanced RIS Gain Modeling (Physically-based simulation)
# Utilizing direct mathematical modeling as seen in professional communication libraries

import numpy as np
import matplotlib.pyplot as plt

def calculate_ris_beamforming_gain(elements_count):
    """
    Calculates the theoretical power gain provided by the RIS based on the number of elements.
    Principle: In ideal beamforming, the gain is proportional to the square of the
    number of elements (N^2).
    """
    N = elements_count
    # Gain in dB = 20 * log10(N)
    # Reflects the coherent combining of signals at the receiver
    gain_db = 20 * np.log10(N)
    return gain_db

# Scenario: A mid-range RIS panel with 256 elements (e.g., 16x16 configuration)
elements = 256
gain = calculate_ris_beamforming_gain(elements)

print(f"--- 6G Technical Research Report ---")
print(f"RIS Element Configuration (N): {elements}")
print(f"Theoretical Beamforming Gain: {gain:.2f} dB")
print(f"Operational Status: Signal link restored in Dead Zone via passive beamforming.")

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def simulate_6g_ris_indoor_environment():
    """
    3D Ray Tracing Simulation for 6G RIS Signal Redirection.
    Demonstrates overcoming Non-Line-of-Sight (NLoS) challenges using
    Reconfigurable Intelligent Surfaces.
    """
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')

    # 1. Environment Setup (Indoor Laboratory/Retail Space)
    ax.set_xlim(0, 10); ax.set_ylim(0, 10); ax.set_zlim(0, 5)
    ax.set_xlabel('Width (m)'); ax.set_ylabel('Length (m)'); ax.set_zlabel('Height (m)')

    # 2. Key Element Coordinates (Stationary & Mobile Nodes)
    tower = np.array([0, 5, 4])          # 6G Micro-cell / Base Station
    ris_panel = np.array([5, 9.8, 2.5])  # RIS Panel mounted on the wall
    phone = np.array([9, 2, 1])          # Mobile User Equipment (UE) behind obstacles

    # 3. Obstacle Modeling (e.g., Shelves/Equipment blocking the signal)
    # Representing the physical barrier causing the NLoS scenario
    x, y, z = np.meshgrid([4, 6], [0, 7], [0, 3])
    ax.plot_surface(np.array([[4,4],[6,6]]), np.array([[0,7],[0,7]]), np.array([[3,3],[3,3]]), color='gray', alpha=0.5)
    ax.text(5, 3.5, 3.5, "Signal Obstacle (NLoS Zone)", color='black', ha='center')

    # 4. Visualizing Components (Base Station, UE, and RIS)
    ax.scatter(*tower, color='blue', s=200, label='6G Base Station')
    ax.scatter(*phone, color='green', s=150, label='Mobile UE (User)')

    # Modeling the RIS Panel as a Reflective Gold Surface
    ris_x = [4.5, 5.5, 5.5, 4.5]
    ris_y = [9.8, 9.8, 9.8, 9.8]
    ris_z = [2, 2, 3, 3]
    ax.plot_trisurf(ris_x, ris_y, ris_z, color='gold', alpha=0.8)
    ax.text(5, 10, 3.2, "Reconfigurable Intelligent Surface", color='orange', fontweight='bold')

    # 5. Ray Tracing Paths (Signal Propagation)
    # Direct Path (Blocked/Severely Attenuated)
    ax.plot([tower[0], phone[0]], [tower[1], phone[1]], [tower[2], phone[2]], color='red', linestyle='--', alpha=0.3, label='Blocked Direct Path')

    # Smart Reflected Path via RIS (Link Restoration)
    # Path A: Base Station to RIS
    ax.plot([tower[0], ris_panel[0]], [tower[1], ris_panel[1]], [tower[2], ris_panel[2]], color='orange', linewidth=3)
    # Path B: RIS to Mobile User (Beamforming)
    ax.plot([ris_panel[0], phone[0]], [ris_panel[1], phone[1]], [ris_panel[2], phone[2]], color='orange', linewidth=3, label='RIS Optimized Beam')

    # 6. Aesthetic Adjustments and Perspective
    ax.view_init(elev=25, azim=-45) # Professional viewing angle
    plt.title("6G Smart Wireless Environment: RIS-Assisted Link Restoration (Simulation 2026)")
    plt.legend()
    plt.show()

# Execute the simulation
simulate_6g_ris_indoor_environment()

import plotly.graph_objects as go
import numpy as np

# 1. Component Coordinates Setup
# BS: Base Station, RIS: Reconfigurable Intelligent Surface, UE: User Equipment
tower = [0, 5, 4]        # 6G Micro-cell Base Station
ris_panel = [5, 9.8, 2.5] # Intelligent Reflective Surface
phone = [9, 2, 1]        # Mobile UE (behind NLoS barrier)

# 2. Modeling the Physical Obstacle (NLoS Barrier)
def create_obstacle_volume(x_range, y_range, z_range, name, color):
    """Generates a 3D mesh to represent physical obstructions in the signal path."""
    x, y, z = np.meshgrid(x_range, y_range, z_range)
    return go.Mesh3d(x=x.flatten(), y=y.flatten(), z=z.flatten(),
                     alphahull=0, name=name, color=color, opacity=0.5)

# Representing shelving units or industrial equipment causing signal blockage
shelf = create_obstacle_volume([4, 6], [0, 7], [0, 3], "Signal Obstacle (NLoS)", "gray")

# 3. Ray Tracing: Intelligent Beam Propagation
# Incident Beam: From Base Station to RIS
beam_in = go.Scatter3d(x=[tower[0], ris_panel[0]], y=[tower[1], ris_panel[1]], z=[tower[2], ris_panel[2]],
                       mode='lines', line=dict(color='orange', width=8), name='Incident 6G Beam')

# Reflected Beam: Optimized path from RIS to User Equipment
beam_out = go.Scatter3d(x=[ris_panel[0], phone[0]], y=[ris_panel[1], phone[1]], z=[ris_panel[2], phone[2]],
                        mode='lines', line=dict(color='gold', width=10), name='RIS Optimized Reflection')

# 4. Device Visualization (Nodes)
nodes = go.Scatter3d(
    x=[tower[0], ris_panel[0], phone[0]],
    y=[tower[1], ris_panel[1], phone[1]],
    z=[tower[2], ris_panel[2], phone[2]],
    mode='markers+text',
    marker=dict(size=[12, 15, 10], color=['blue', 'gold', 'green'], symbol=['diamond', 'square', 'circle']),
    text=["6G Base Station", "RIS Intelligent Panel", "Mobile UE"],
    textposition="top center",
    name='Network Nodes'
)

# 5. Scene Integration
fig = go.Figure(data=[shelf, beam_in, beam_out, nodes])

# 6. Interactive Visualization Settings
fig.update_layout(
    title="Interactive 6G RIS Simulation: Overcoming NLoS Obstructions",
    scene=dict(
        xaxis_title='Width (m)',
        yaxis_title='Length (m)',
        zaxis_title='Height (m)',
        aspectmode='manual',
        aspectratio=dict(x=1, y=1, z=0.5),
    ),
    margin=dict(l=0, r=0, b=0, t=40)
)

fig.show()

import plotly.graph_objects as go
import numpy as np

# 1. Component Coordinates Setup
# BS: Base Station, RIS: Reconfigurable Intelligent Surface, UE: User Equipment
tower = [0, 5, 4]        # 6G Micro-cell Base Station
ris_panel = [5, 9.8, 2.5] # Intelligent Reflective Surface
phone = [9, 2, 1]        # Mobile UE (behind NLoS barrier)

# 2. Modeling the Physical Obstacle (NLoS Barrier)
def create_obstacle_volume(x_range, y_range, z_range, name, color):
    """Generates a 3D mesh to represent physical obstructions in the signal path."""
    x, y, z = np.meshgrid(x_range, y_range, z_range)
    return go.Mesh3d(x=x.flatten(), y=y.flatten(), z=z.flatten(),
                     alphahull=0, name=name, color=color, opacity=0.5)

# Representing physical barriers causing signal blockage (Non-Line-of-Sight scenario)
shelf = create_obstacle_volume([4, 6], [0, 7], [0, 3], "Signal Obstacle (NLoS)", "gray")

# 3. Ray Tracing: Intelligent Beam Propagation
# Incident Beam: From Base Station to RIS
beam_in = go.Scatter3d(x=[tower[0], ris_panel[0]], y=[tower[1], ris_panel[1]], z=[tower[2], ris_panel[2]],
                       mode='lines', line=dict(color='orange', width=8), name='Incident 6G Beam')

# Reflected Beam: Optimized path from RIS to User Equipment
beam_out = go.Scatter3d(x=[ris_panel[0], phone[0]], y=[ris_panel[1], phone[1]], z=[ris_panel[2], phone[2]],
                        mode='lines', line=dict(color='gold', width=10), name='RIS Optimized Reflection')

# 4. Device Visualization (Network Nodes)
nodes = go.Scatter3d(
    x=[tower[0], ris_panel[0], phone[0]],
    y=[tower[1], ris_panel[1], phone[1]],
    z=[tower[2], ris_panel[2], phone[2]],
    mode='markers+text',
    marker=dict(size=[12, 15, 10], color=['blue', 'gold', 'green'], symbol=['diamond', 'square', 'circle']),
    text=["6G Base Station", "RIS Intelligent Panel", "Mobile UE"],
    textposition="top center",
    name='Network Nodes'
)

# 5. Scene Integration
fig = go.Figure(data=[shelf, beam_in, beam_out, nodes])

# 6. Interactive Visualization Settings
fig.update_layout(
    title="Interactive 6G RIS Simulation: Overcoming NLoS Obstructions",
    scene=dict(
        xaxis_title='Width (m)',
        yaxis_title='Length (m)',
        zaxis_title='Height (m)',
        aspectmode='manual',
        aspectratio=dict(x=1, y=1, z=0.5),
    ),
    margin=dict(l=0, r=0, b=0, t=40)
)

fig.show()

import plotly.graph_objects as go
import numpy as np

# 1. Trajectory Setup: Modeling Mobile User Movement (UE)
# Simulating a user moving from a Non-Line-of-Sight (NLoS) zone to the checkout area
frames_count = 50
t = np.linspace(0, 1, frames_count)

# Path coordinates for the Mobile Device
phone_path_x = 9 - 6 * t
phone_path_y = 2 + 6 * t
phone_path_z = np.ones(frames_count)

# 2. Static Nodes: 6G Base Station and RIS Smart Panel
tower = [0, 5, 4]         # 6G Micro-cell
ris_panel = [5, 9.8, 2.5]  # RIS Phase-shift Controller

# 3. Initial Frame Setup (Time = 0)
fig = go.Figure(
    data=[
        # Signal Obstacle (Physical Barrier)
        go.Mesh3d(x=[4,6,4,6,4,6,4,6], y=[0,0,7,7,0,0,7,7], z=[0,0,0,0,3,3,3,3],
                  alphahull=0, color='gray', opacity=0.4, name="NLoS Barrier"),

        # Incident Beam: Stationary link between Base Station and RIS
        go.Scatter3d(x=[tower[0], ris_panel[0]], y=[tower[1], ris_panel[1]], z=[tower[2], ris_panel[2]],
                     mode='lines', line=dict(color='blue', width=6), name="Incident 6G Link"),

        # Dynamic Reflected Beam: Real-time Beam Tracking via RIS
        go.Scatter3d(x=[ris_panel[0], phone_path_x[0]], y=[ris_panel[1], phone_path_y[0]], z=[ris_panel[2], phone_path_z[0]],
                     mode='lines', line=dict(color='orange', width=10), name="Adaptive RIS Beam"),

        # Mobile User Equipment (UE)
        go.Scatter3d(x=[phone_path_x[0]], y=[phone_path_y[0]], z=[phone_path_z[0]],
                     mode='markers', marker=dict(size=10, color='green'), name="Mobile UE")
    ],
    layout=go.Layout(
        title="6G RIS Dynamic Beam Tracking Simulation",
        scene=dict(
            xaxis=dict(range=[0, 10], title="Width (m)"),
            yaxis=dict(range=[0, 10], title="Length (m)"),
            zaxis=dict(range=[0, 5], title="Height (m)")
        ),
        updatemenus=[dict(type="buttons", buttons=[dict(label="Execute Tracking", method="animate", args=[None])])]
    ),
    frames=[go.Frame(
        data=[
            # Updating the Reflected Beam and UE position for each frame
            go.Scatter3d(x=[ris_panel[0], phone_path_x[k]], y=[ris_panel[1], phone_path_y[k]], z=[ris_panel[2], phone_path_z[k]]),
            go.Scatter3d(x=[phone_path_x[k]], y=[phone_path_y[k]], z=[phone_path_z[k]])
        ],
        traces=[2, 3] # Targets the dynamic components
    ) for k in range(frames_count)]
)

fig.show()

import numpy as np
import matplotlib.pyplot as plt

# 1. Spatial Grid Configuration (Environment setup around the User)
grid_size = 100
x = np.linspace(-5, 5, grid_size)
y = np.linspace(0, 10, grid_size)
X, Y = np.meshgrid(x, y)

# 2. Target Localization (Point of Maximum Beamforming Gain)
target_x, target_y = 0, 7  # Designated User Equipment (UE) position

# 3. Beamforming Gain Modeling
# Simulating the energy concentration provided by the RIS using a Gaussian Distribution
# Sigma represents the 'Beamwidth' (Lower sigma = Narrower, more precise beam)
sigma = 0.8
power_dist = np.exp(-((X - target_x)**2 + (Y - target_y)**2) / (2 * sigma**2))

# 4. Stochastic Environmental Noise (Real-world Modeling)
# Adding Gaussian Noise to simulate interference and multi-path effects
noise = np.random.normal(0, 0.05, power_dist.shape)
final_signal_distribution = power_dist + noise

# 5. Spatial Signal Intensity Heatmap Visualization
plt.figure(figsize=(10, 8))
cp = plt.contourf(X, Y, final_signal_distribution, cmap='hot', levels=50)
plt.colorbar(cp, label='Normalized Signal Intensity (Gain)')

# Plotting the RIS Source and the Target Focal Point
plt.scatter(0, 0, color='gold', s=300, marker='s', label='RIS Surface (Source)')
plt.scatter(target_x, target_y, color='cyan', s=200, marker='*', label='Target UE (Focus Point)')

plt.title("Spatial Energy Distribution via RIS Beamforming (6G Simulation)")
plt.xlabel("Horizontal Displacement (m)")
plt.ylabel("Longitudinal Distance from RIS (m)")
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

# 1. Spatial Configuration
# RIS Surface positioned at the center of the wall
ris_pos = np.array([5, 0])
# Simulating User Equipment (UE) trajectory along a linear path
ue_path_x = np.linspace(1, 9, 20)
ue_path_y = np.linspace(8, 8, 20)

def calculate_beam_steering_angle(ris_coord, target_coord):
    """
    Calculates the required Phase Shift/Steering Angle to focus the beam.
    Uses Trigonometric functions to determine the Angle of Departure (AoD).
    """
    dy = target_coord[1] - ris_coord[1]
    dx = target_coord[0] - ris_coord[0]
    angle = np.degrees(np.arctan2(dy, dx))
    return angle

# 2. Real-Time Tracking Simulation Loop
for i in range(len(ue_path_x)):
    current_ue_pos = np.array([ue_path_x[i], ue_path_y[i]])
    steering_angle = calculate_beam_steering_angle(ris_pos, current_ue_pos)

    # Visualization of Adaptive Beamforming
    plt.figure(figsize=(8, 6))
    plt.xlim(0, 10); plt.ylim(-1, 10)

    # Plotting RIS Panel and Mobile UE
    plt.scatter(ris_pos[0], ris_pos[1], color='gold', s=400, marker='s', label='RIS Controller')
    plt.scatter(current_ue_pos[0], current_ue_pos[1], color='green', s=100, label='Mobile UE (Moving)')

    # Visualizing the Dynamic Steering Beam
    plt.plot([ris_pos[0], current_ue_pos[0]], [ris_pos[1], current_ue_pos[1]],
             color='orange', linewidth=4, alpha=0.6, linestyle='--')

    plt.title(f"Adaptive 6G Beam Tracking\nCalculated Steering Angle (AoD) = {steering_angle:.2f}°")
    plt.xlabel("X-Axis (m)")
    plt.ylabel("Y-Axis (m)")
    plt.legend(loc='upper right')
    plt.grid(True, alpha=0.3)

    plt.show()
    time.sleep(0.1)
    clear_output(wait=True)

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, FloatSlider, IntSlider

def update_6g_performance_simulation(ue_x, ue_y, num_elements):
    """
    Real-time 6G Performance Analysis Tool.
    Evaluates the impact of RIS surface size and user location on
    Signal Strength (dBm) and Achievable Data Rates (Gbps).
    """
    # 1. Spatial Configuration
    ris_pos = np.array([5, 0])
    target_ue = np.array([ue_x, ue_y])

    # 2. Geometric Beam Steering Calculation
    dx = target_ue[0] - ris_pos[0]
    dy = target_ue[1] - ris_pos[1]
    steering_angle = np.degrees(np.arctan2(dy, dx))

    # 3. Link Budget & Performance Metrics
    # RSSI calculation based on RIS Gain (proportional to N^2) and Path Loss
    distance = np.sqrt(dx**2 + dy**2)

    # Gain calculation (N^2 principle for coherent beamforming)
    ris_gain = 10 * np.log10(num_elements**2)

    # Simplified Free Space Path Loss (FSPL) model
    path_loss = 20 * np.log10(distance + 1)

    # Estimated Received Signal Strength Indicator (RSSI)
    rssi = ris_gain - path_loss + 20 # Normalized baseline

    # Theoretical 6G Throughput (Gbps) estimation
    # Mapping signal quality to Shannon capacity-inspired metrics
    throughput_gbps = max(0, (rssi + 50) * 0.1)

    # 4. Data Visualization
    plt.figure(figsize=(14, 6))

    # Subplot A: Spatial Environment & Beam Alignment
    plt.subplot(1, 2, 1)
    plt.xlim(0, 10); plt.ylim(-1, 10)
    plt.scatter(ris_pos[0], ris_pos[1], color='gold', s=400, marker='s', label='RIS Controller')
    plt.scatter(target_ue[0], target_ue[1], color='green', s=150, marker='o', label='Mobile UE')

    # Visualize beamwidth based on element count
    plt.plot([ris_pos[0], target_ue[0]], [ris_pos[1], target_ue[1]],
             'orange', linewidth=num_elements/64, alpha=0.6)

    plt.title(f"Spatial Alignment | Angle: {steering_angle:.1f}°")
    plt.xlabel("Width (m)")
    plt.ylabel("Distance (m)")
    plt.legend(loc='upper right')
    plt.grid(True, alpha=0.2)

    # Subplot B: Performance Analytics (KPIs)
    plt.subplot(1, 2, 2)
    kpis = ['Signal (dBm)', 'Throughput (Gbps)']
    values = [rssi, throughput_gbps]
    colors = ['#1f77b4', '#2ca02c'] # Professional color palette

    plt.bar(kpis, values, color=colors)
    plt.ylim(0, 100 if rssi > 0 else 10)
    plt.title("Real-time 6G KPI Analytics")
    plt.ylabel("Calculated Metrics")

    plt.tight_layout()
    plt.show()

# Interactive Control Interface
interact(update_6g_performance_simulation,
         ue_x=FloatSlider(min=0, max=10, step=0.1, value=2, description='UE X-Pos:'),
         ue_y=FloatSlider(min=1, max=9, step=0.1, value=7, description='UE Y-Pos:'),
         num_elements=IntSlider(min=16, max=1024, step=16, value=256, description='RIS Elements (N):'))

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, IntSlider

def simulate_multi_user_ris_steering(num_users):
    """
    Simulates Multi-User Beamforming in a 6G Environment.
    Demonstrates Spatial Multiplexing where a single RIS surface provides
    dedicated service to multiple User Equipments (UEs).
    """
    ris_pos = np.array([5, 0])
    plt.figure(figsize=(10, 8))

    # Deterministic seeding for consistent spatial distribution during testing
    np.random.seed(42)
    user_colors = ['#2ca02c', '#17becf', '#e377c2', '#bcbd22', '#7f7f7f', '#ff7f0e']

    for i in range(num_users):
        # Generating random spatial coordinates for UEs within the environment
        ue_x = np.random.uniform(1, 9)
        ue_y = np.random.uniform(3, 9)

        # Plotting the User Equipment (UE)
        plt.scatter(ue_x, ue_y, color=user_colors[i % len(user_colors)],
                    s=150, label=f'UE {i+1}', edgecolors='white', zorder=3)

        # Modeling Multi-Beam Steering
        # Note: Beam intensity (alpha) scales inversely with the number of users
        # to reflect power splitting/resource allocation across multiple links.
        alpha_val = max(0.2, 1.0 / num_users)
        plt.plot([ris_pos[0], ue_x], [ris_pos[1], ue_y],
                 color='orange', linewidth=2, alpha=alpha_val, zorder=2)

    # Plotting the RIS Surface (Phase-Array Controller)
    plt.scatter(ris_pos[0], ris_pos[1], color='gold', s=400, marker='s',
                label='RIS Panel', edgecolors='black', zorder=4)

    plt.xlim(0, 10); plt.ylim(-1, 10)
    plt.title(f"6G Multi-User MIMO Simulation: {num_users} Active Beams")
    plt.xlabel("Spatial Width (m)")
    plt.ylabel("Distance (m)")
    plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
    plt.grid(True, alpha=0.2, linestyle='--')
    plt.show()

# Interactive Interface for Multi-User Resource Allocation
interact(simulate_multi_user_ris_steering,
         num_users=IntSlider(min=1, max=10, step=1, value=3, description='Active UEs:'))

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

# 1. Environment and User Configuration
num_users = 5
ris_pos = np.array([5, 0])  # Stationary RIS Surface
# Initial spatial distribution of User Equipments (UEs)
ue_positions = np.random.uniform(2, 8, (num_users, 2))

# 2. Dynamic Tracking Simulation Loop (30 Time-Steps)
for frame in range(30):
    clear_output(wait=True)
    plt.figure(figsize=(10, 8))

    # Plotting the RIS Controller
    plt.scatter(ris_pos[0], ris_pos[1], color='gold', s=400, marker='s',
                label='RIS Panel', edgecolors='black', zorder=5)

    for i in range(num_users):
        # Modeling Stochastic Mobility (Random Walk Model)
        # Simulating slight movements of users within the environment
        ue_positions[i] += np.random.uniform(-0.3, 0.3, 2)

        # Boundary constraints: Ensuring UEs stay within the simulated area
        ue_positions[i] = np.clip(ue_positions[i], 1, 9)

        current_pos = ue_positions[i]

        # Visualizing the UE and the Adaptive Tracking Beam
        plt.scatter(current_pos[0], current_pos[1], s=150, edgecolors='white',
                    label=f'UE {i+1}', zorder=4)

        # Incident beam redirection modeled with transparency to reflect multi-user link budget
        plt.plot([ris_pos[0], current_pos[0]], [ris_pos[1], current_pos[1]],
                 'orange', alpha=0.4, linewidth=2, zorder=3)

    # 3. Visualization Metadata
    plt.xlim(0, 10); plt.ylim(-1, 10)
    plt.title(f"Dynamic 6G Beam Tracking Simulation\nReal-time Localization - Frame {frame}")
    plt.xlabel("X-Coordinate (m)")
    plt.ylabel("Y-Coordinate (m)")
    plt.grid(alpha=0.2, linestyle='--')
    # Placing the legend outside to keep the plot clean
    plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))

    plt.show()
    time.sleep(0.1)

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

# 1. Environment and Propagation Obstacle Setup
ris_pos = np.array([5, 0])
# Defining a physical obstruction (e.g., heavy shelving) causing NLoS conditions
obstacle_rect = {'x': [3, 7], 'y': [4, 5.5]}
num_users = 3
# Positioning User Equipments (UEs) in the shadowed region behind the obstacle
ue_positions = np.array([[2, 8], [5, 8], [8, 8]], dtype=float)

# 2. Dynamic Simulation: Link Restoration via RIS
for frame in range(40):
    clear_output(wait=True)
    plt.figure(figsize=(10, 8))

    # Plotting Environment Boundaries and the RIS Controller
    plt.axhline(0, color='black', linewidth=3)
    plt.scatter(ris_pos[0], ris_pos[1], color='gold', s=500, marker='s',
                label='Smart RIS Panel', edgecolors='black', zorder=6)

    # Modeling the Physical Obstacle (Signal Attenuation Zone)
    obstacle = plt.Rectangle((obstacle_rect['x'][0], obstacle_rect['y'][0]),
                             obstacle_rect['x'][1]-obstacle_rect['x'][0],
                             obstacle_rect['y'][1]-obstacle_rect['y'][0],
                             color='darkred', alpha=0.7, label='NLoS Obstacle (Signal Blockage)')
    plt.gca().add_patch(obstacle)

    for i in range(num_users):
        # Stochastic UE micro-mobility modeling
        ue_positions[i][0] += np.random.uniform(-0.2, 0.2)
        pos = ue_positions[i]

        # Plotting the Mobile User Equipment (UE)
        plt.scatter(pos[0], pos[1], s=200, color='green', edgecolors='white', zorder=5)

        # Visualizing the Smart Redirected Path
        # Demonstrating the RIS capability to establish a virtual LoS link
        # to users in the shadowed zone.
        plt.plot([ris_pos[0], pos[0]], [ris_pos[1], pos[1]],
                 color='cyan', alpha=0.6, linewidth=3, linestyle='--',
                 label='RIS-Assisted Smart Path' if i==0 else "")

    # Simulation Metadata and Scaling
    plt.xlim(0, 10); plt.ylim(-1, 10)
    plt.title(f"6G RIS Link Restoration: Overcoming NLoS Obstructions\nSimulation Frame: {frame}")
    plt.xlabel("Spatial Width (m)")
    plt.ylabel("Spatial Depth (m)")
    plt.legend(loc='lower right')
    plt.grid(alpha=0.1)

    plt.show()
    time.sleep(0.1)

import matplotlib.pyplot as plt

# Comparative metrics based on 2026 6G RIS propagation studies
scenarios = ['Standard (Dead Zone)', 'RIS-Enhanced Link']
# Received Signal Strength Indicator (RSSI) in dBm
signal_strength = [-95, -45]
# Achievable Data Rate (Throughput) in Gbps
throughput_gbps = [0.05, 15.5]

plt.figure(figsize=(12, 5))

# 1. Signal Intensity Comparison (dBm)
plt.subplot(1, 2, 1)
bars1 = plt.bar(scenarios, signal_strength, color=['#d62728', '#2ca02c'])
plt.ylabel('Signal Strength (dBm)')
plt.title('RSSI Evaluation Behind Obstructions')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Adding data labels for precision
for bar in bars1:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval - 5, f"{yval} dBm",
             ha='center', color='black', fontweight='bold')

# 2. Network Throughput Comparison (Gbps)
plt.subplot(1, 2, 2)
bars2 = plt.bar(scenarios, throughput_gbps, color=['#d62728', '#1f77b4'])
plt.ylabel('Data Rate (Gbps)')
plt.title('Throughput Restoration Performance')
plt.grid(axis='y', linestyle='--', alpha=0.7)

for bar in bars2:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.5, f"{yval} Gbps",
             ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

import numpy as np

class AIRISController:
    """
    AI-Driven RIS Beamforming Controller.
    Uses a simplified Reinforcement Learning (RL) approach to optimize
    the Phase-Shift Matrix based on signal feedback (RSSI).
    """
    def __init__(self, num_elements=256):
        self.num_elements = num_elements
        # Phase Matrix (Controlled by the AI Agent)
        # Initialized with random phases between [0, 2π]
        self.phase_matrix = np.random.uniform(0, 2*np.pi, num_elements)
        self.learning_rate = 0.1

    def get_signal_feedback(self, ue_pos, current_phases):
        """
        Simulates the feedback link from the User Equipment (UE).
        In a real 6G network, the UE reports the RSSI back to the RIS controller.
        """
        # Target/Optimal phases based on the geometric channel model
        optimal_phases = np.full(self.num_elements, 0.5)

        # Calculate the phase deviation (Error)
        error = np.mean(np.abs(optimal_phases - current_phases))

        # Reward function: Higher signal strength leads to higher reward
        reward = 1.0 / (error + 0.1)
        return reward

    def optimize_beamforming(self, ue_pos):
        """
        The Learning Loop (Policy Optimization).
        Adjusts the phase configuration to maximize the Received Signal Strength.
        """
        current_reward = self.get_signal_feedback(ue_pos, self.phase_matrix)

        # Apply a Stochastic Perturbation (Exploration step)
        adjustment = np.random.normal(0, 0.1, self.num_elements)
        trial_phases = self.phase_matrix + adjustment

        new_reward = self.get_signal_feedback(ue_pos, trial_phases)

        # Policy Update: If the trial phases yield better performance, update the matrix
        if new_reward > current_reward:
            self.phase_matrix = trial_phases
            return new_reward, "Optimization Successful"
        else:
            return current_reward, "Exploring Optimal States..."

# --- Simulation Execution ---
# Initializing the AI Agent
ai_agent = AIRISController(num_elements=256)

print("Starting 6G AI-RIS Optimization Sequence...")
print("-" * 50)

for step in range(10):
    strength, status = ai_agent.optimize_beamforming(ue_pos=[2, 7])
    print(f"Step {step+1:02d} | Received Gain: {strength:.4f} | Status: {status}")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def generate_isac_heatmap():
    """
    Simulates 6G ISAC (Integrated Sensing and Communication).
    This function generates a Radar Occupancy Map by processing reflected
    echoes from objects/users within the environment.
    """
    # 1. Spatial Grid Configuration (10x10 meters shop area)
    grid_size = 50
    sensing_matrix = np.zeros((grid_size, grid_size))
    # RIS Positioned at the center of the left boundary
    ris_source_pos = [0, 25]

    # 2. Modeling Detected Echoes (Radar Cross Section - RCS)
    # Positions of 3 detected entities (Customers/Objects)
    entities = [(15, 10), (35, 30), (20, 40)]

    for (cx, cy) in entities:
        # Simulating Radar wave propagation and reflection backscatter
        for x in range(grid_size):
            for y in range(grid_size):
                distance_to_entity = np.sqrt((x-cx)**2 + (y-cy)**2)
                # Power of the reflected 'Echo' modeled with a Gaussian Decay
                # This represents the sensing resolution and signal intensity
                sensing_matrix[x, y] += np.exp(-distance_to_entity**2 / 15.0)

    # 3. Visualization: ISAC Occupancy Heatmap
    plt.figure(figsize=(10, 8))
    # Using 'magma' colormap to emphasize high-intensity sensing zones
    sns.heatmap(sensing_matrix, cmap='magma', cbar_kws={'label': 'Reflected Signal Intensity (Sensing)'})

    # Plotting the Integrated Source (RIS acting as a Radar/Transmitter)
    plt.scatter(ris_source_pos[1], ris_pos[0], color='cyan', s=300, marker='s', label='ISAC-Enabled RIS')

    plt.title("6G ISAC: Real-time Radar Occupancy & Localization Map")
    plt.xlabel("Spatial Width (Grid Units)")
    plt.ylabel("Spatial Depth (Grid Units)")
    plt.legend(loc='upper right')
    plt.show()

# Execute the ISAC Sensing Simulation
generate_isac_heatmap()

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 1. Environment & AI Agent Configuration
fig, ax = plt.subplots(figsize=(10, 7))
ris_pos = np.array([5, 0])  # RIS Controller position
num_users = 2
# Initial spatial coordinates for User Equipment (UE)
ue_pos = np.array([[2.0, 8.0], [8.0, 7.0]])
velocities = np.random.uniform(-0.05, 0.05, (num_users, 2))

# Phase-shift angles that the AI agent will learn to optimize
# Initialized randomly to simulate an untrained state
learned_angles = np.random.uniform(0, 180, num_users)

# Visualization Elements
scat = ax.scatter([], [], s=250, c='dodgerblue', edgecolors='white', zorder=3, label='Mobile UEs')
beams = [ax.plot([], [], color='orange', lw=2, alpha=0.3)[0] for _ in range(num_users)]
status_text = ax.text(0.5, 9.5, "", fontsize=12, fontweight='bold', color='darkgreen')

def update_simulation_frame(frame):
    """
    Core Simulation Loop: Performs UE mobility update and
    executes the Reinforcement Learning (RL) beam-locking logic.
    """
    global ue_pos, learned_angles

    # Modeling UE Mobility: Update positions based on velocity vectors
    ue_pos += velocities

    # Boundary Constraints: Reflective walls logic
    for i in range(num_users):
        if ue_pos[i,0] < 1 or ue_pos[i,0] > 9: velocities[i,0] *= -1
        if ue_pos[i,1] < 2 or ue_pos[i,1] > 9: velocities[i,1] *= -1

    # AI Beamforming Optimization (Simplified RL Logic)
    current_network_status = "AI-Driven RIS Status: "

    for i in range(num_users):
        # Calculate the Ground Truth (Ideal Steering Angle)
        target_angle = np.degrees(np.arctan2(ue_pos[i, 1] - ris_pos[1], ue_pos[i, 0] - ris_pos[0]))

        # Calculate Angular Deviation (The Error Signal for the AI)
        angular_error = target_angle - learned_angles[i]

        if abs(angular_error) > 2:
            # State: SEARCHING/LEARNING
            # The AI takes a 'Learning Step' to minimize the error
            learned_angles[i] += np.random.normal(angular_error * 0.2, 5)
            beams[i].set_alpha(0.2) # Weak signal indicator during search
            beams[i].set_linestyle('--')
            current_network_status += f"UE{i+1}: Tracking.. "
        else:
            # State: LOCKED/STABLE
            # AI has successfully converged on the UE's location
            learned_angles[i] = target_angle
            beams[i].set_alpha(0.9) # High-gain beam lock
            beams[i].set_linestyle('-')
            current_network_status += f"UE{i+1}: Locked! "

        # Project the beam based on the AI's 'Learned' angle
        rad = np.radians(learned_angles[i])
        length = np.sqrt(np.sum((ue_pos[i]-ris_pos)**2))
        end_x = ris_pos[0] + length * np.cos(rad)
        end_y = ris_pos[1] + length * np.sin(rad)
        beams[i].set_data([ris_pos[0], end_x], [ris_pos[1], end_y])

    scat.set_offsets(ue_pos)
    status_text.set_text(current_network_status)
    return [scat, status_text] + beams

# Configure and Execute the Animation
ani = FuncAnimation(fig, update_simulation_frame, frames=150, interval=60, blit=True)
plt.xlim(0, 10); plt.ylim(-1, 10)
plt.title("AI-Native 6G RIS: Real-time Multi-UE Beam Locking")
plt.xlabel("Spatial Width (m)")
plt.ylabel("Spatial Depth (m)")
plt.grid(alpha=0.3, linestyle='--')
plt.close() # Prevents static plot from displaying

# Generate and display the video output
HTML(ani.to_html5_video())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 1. Environment & Network Capacity Configuration
fig, ax = plt.subplots(figsize=(12, 8))
ris_pos = np.array([5, 0])
max_capacity = 10
# Using a Jet colormap to distinguish individual User Equipments (UEs)
colors = plt.cm.jet(np.linspace(0, 1, max_capacity))

# UE State Initialization
ue_positions = np.random.uniform(2, 8, (max_capacity, 2))
velocities = np.random.uniform(-0.1, 0.1, (max_capacity, 2))
# Simulation starts with 2 active users; others join during the 'Flash Crowd' event
active_mask = np.array([True, True] + [False]*(max_capacity-2))

# Graphical Elements for Network Visualization
scat = ax.scatter([], [], s=150, edgecolors='black', zorder=3, label='Active UEs')
beams = [ax.plot([], [], color=colors[i], alpha=0, lw=1.5)[0] for i in range(max_capacity)]
network_status_text = ax.text(0.5, 9.2, "", fontsize=12, fontweight='bold',
                             bbox=dict(facecolor='white', alpha=0.7))

def update_network_state(frame):
    """
    Simulates real-time AI decision-making for resource allocation.
    Includes a 'Flash Crowd' event at frame 50 to test network elasticity.
    """
    global active_mask, ue_positions

    # Triggering the Flash Crowd Event (Sudden demand surge)
    if frame == 50:
        active_mask[:] = True

    # Spatial update for active UEs only
    ue_positions[active_mask] += velocities[active_mask]

    # Kinetic Boundary Logic: Reflective mobility model
    for i in range(max_capacity):
        if active_mask[i]:
            # Boundary collision detection
            if ue_positions[i,0] < 0.5 or ue_positions[i,0] > 9.5: velocities[i,0] *= -1
            if ue_positions[i,1] < 1   or ue_positions[i,1] > 9.5: velocities[i,1] *= -1

            # AI Resource Allocation Strategy:
            # Power density is adjusted based on the total active load.
            # Coherent beamforming vs. Multi-user spatial multiplexing.
            num_active = np.sum(active_mask)
            beam_alpha = 0.8 if num_active <= 2 else 0.3 # Power splitting simulation

            beams[i].set_data([ris_pos[0], ue_positions[i, 0]], [ris_pos[1], ue_positions[i, 1]])
            beams[i].set_alpha(beam_alpha)
        else:
            beams[i].set_alpha(0)

    # Rendering active UEs with their respective color-coded IDs
    scat.set_offsets(ue_positions[active_mask])
    scat.set_color(colors[active_mask])

    # Dynamic KPI Reporting
    strategy = "High-Gain Targeted Beam" if np.sum(active_mask) <= 2 else "Multi-User Load Balancing"
    status = f"Active UEs: {np.sum(active_mask)} | AI Strategy: {strategy}"
    network_status_text.set_text(status)

    return [scat, network_status_text] + beams

# Animation Engine Configuration
ani = FuncAnimation(fig, update_network_state, frames=150, interval=80, blit=True)
ax.set_xlim(0, 10); ax.set_ylim(-1, 10)
ax.scatter(ris_pos[0], ris_pos[1], color='gold', s=500, marker='s', label='6G RIS Node', edgecolors='black')
ax.set_title("6G Network Elasticity Simulation: Sudden Load Management via RIS")
ax.set_xlabel("Spatial Width (m)"); ax.set_ylabel("Spatial Depth (m)")
plt.close()

# Generate the simulation video output
HTML(ani.to_html5_video())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 1. Environment & Network Protocol Configuration
fig, ax = plt.subplots(figsize=(10, 7))
ris_pos = np.array([5, 0])
max_users = 8
# Initial spatial distribution for User Equipments (UEs)
ue_positions = np.random.uniform(2, 8, (max_users, 2))
velocities = np.random.uniform(-0.06, 0.06, (max_users, 2))

# Network State Matrix
# 0: Idle/Disconnected, 1: Beam Training/Handshaking, 2: Stable Data Link
ue_status = np.zeros(max_users)
# Latency counter simulating the time required for successful Beam Alignment
connection_timers = np.zeros(max_users)

# Visualization Components
scat = ax.scatter([], [], s=150, edgecolors='black', zorder=3, label='Mobile UEs')
beams = [ax.plot([], [], lw=1.5)[0] for i in range(max_users)]

def update_network_protocol(frame):
    """
    Simulates the 6G Connection Lifecycle:
    Stochastic arrival -> Beam Training (Pilot Signaling) -> Stable Link Establishment.
    """
    global ue_status, connection_timers

    # 1. Stochastic UE Arrival Logic (Simulating users entering the shop)
    if frame % 10 == 0 and np.any(ue_status == 0):
        inactive_indices = np.where(ue_status == 0)[0]
        new_ue_index = np.random.choice(inactive_indices)
        ue_status[new_ue_index] = 1 # Transition to 'Initial Access' state
        connection_timers[new_ue_index] = 20 # Requires 20 frames for Beam Training

    # 2. Update Spatial Mobility and Connection State
    active_mask = np.where(ue_status > 0)[0]
    ue_positions[active_mask] += velocities[active_mask]

    for i in range(max_users):
        if ue_status[i] == 1:
            # PHASE: Beam Training / Pilot Signaling
            # Modeling the overhead required to find the optimal Phase-Shift configuration
            connection_timers[i] -= 1
            beams[i].set_data([ris_pos[0], ue_positions[i,0]], [ris_pos[1], ue_positions[i,1]])
            beams[i].set_color('gray')
            beams[i].set_linestyle(':') # Dotted line representing discovery phase
            beams[i].set_alpha(0.4)

            if connection_timers[i] <= 0:
                ue_status[i] = 2 # Successful Handover to Data Transmission state

        elif ue_status[i] == 2:
            # PHASE: Established Stable Data Link
            # Coherent beamforming providing high-gain connectivity
            beams[i].set_data([ris_pos[0], ue_positions[i,0]], [ris_pos[1], ue_positions[i,1]])
            beams[i].set_color('lime') # Green indicates a high-speed 6G link
            beams[i].set_linestyle('-')
            beams[i].set_alpha(0.8)
        else:
            # UE is currently inactive or out of range
            beams[i].set_alpha(0)

    # Rendering current active UEs
    scat.set_offsets(ue_positions[ue_status > 0])
    return [scat] + beams

# 3. Animation Engine Execution
ani = FuncAnimation(fig, update_network_protocol, frames=200, interval=50, blit=True)
ax.set_xlim(0, 10); ax.set_ylim(-1, 10)
ax.set_title("6G Protocol Simulation: Dynamic Beam Training & Connection Latency")
ax.set_xlabel("Spatial Width (m)")
ax.set_ylabel("Spatial Depth (m)")
ax.grid(alpha=0.3, linestyle='--')
plt.close()

# Export simulation to HTML5 Video
HTML(ani.to_html5_video())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.colors import LinearSegmentedColormap
from IPython.display import HTML

# 1. Environment & Physical Parameter Configuration
fig, ax = plt.subplots(figsize=(12, 8))
ris_pos = np.array([5, 0])
max_users = 3
grid_res = 100  # Resolution of the spatial electromagnetic field map
# Generating the spatial coordinate grid
X, Y = np.meshgrid(np.linspace(0, 10, grid_res), np.linspace(0, 10, grid_res))

# UE Mobility Initialization
ue_positions = np.random.uniform(2, 8, (max_users, 2))
velocities = np.random.uniform(-0.08, 0.08, (max_users, 2))

# Custom Colormap: Visualizing signal intensity from transparent to high-energy orange
colors = [(1, 1, 1, 0), (1, 1, 1, 1), (1, 0.5, 0, 1)] # RGBA
custom_cmap = LinearSegmentedColormap.from_list('beam_intensity_map', colors)

# Graphical Elements
scat = ax.scatter([], [], s=200, color='darkblue', edgecolors='white', zorder=5, label='Active UEs')
# Initializing the Beam Field as a Heatmap
beam_field = ax.imshow(np.zeros((grid_res, grid_res)), cmap=custom_cmap,
                        extent=[0, 10, 0, 10], origin='lower', alpha=0.9, zorder=2)

def calculate_spatial_beam_power(grid_X, grid_Y, target_ue_pos, source_ris_pos):
    """
    Mathematical modeling of 6G Beamforming Gain.
    Calculates power distribution based on angular alignment and radial focus.
    """
    # Calculate grid-wide coordinates relative to the RIS
    dx = grid_X - source_ris_pos[0]
    dy = grid_Y - source_ris_pos[1]
    angles = np.arctan2(dy, dx)
    distances = np.sqrt(dx**2 + dy**2)

    # Calculate targeted User Equipment (UE) coordinates
    dx_ue = target_ue_pos[0] - source_ris_pos[0]
    dy_ue = target_ue_pos[1] - source_ris_pos[1]
    target_angle = np.arctan2(dy_ue, dx_ue)
    target_distance = np.sqrt(dx_ue**2 + dy_ue**2)

    # Modeling Directional Gain: Gaussian Angular Distribution
    # beam_width simulates the AI's ability to sharpen the signal concentration
    beam_width = 0.1
    angular_gain = np.exp(-(angles - target_angle)**2 / (2 * beam_width**2))

    # Path Loss Modeling: Signal attenuation over spatial distance
    attenuation = 1.0 / (distances + 1)

    # Distance Focusing (Radial Gain):
    # Simulates constructive interference at the specific focal point of the UE
    radial_focus = np.exp(-(distances - target_distance)**2 / 2.0)

    return angular_gain * attenuation * radial_focus

def update_field_simulation(frame):
    """
    Real-time field update loop.
    Calculates the cumulative energy field for all active UEs.
    """
    global ue_positions, velocities
    ue_positions += velocities

    # Kinetic Constraints: Boundary Reflection
    for i in range(max_users):
        if ue_positions[i,0] < 1 or ue_positions[i,0] > 9: velocities[i,0] *= -1
        if ue_positions[i,1] < 1 or ue_positions[i,1] > 9: velocities[i,1] *= -1

    # Summing the spatial power distribution for multi-user support
    total_energy_field = np.zeros((grid_res, grid_res))
    for i in range(max_users):
        total_energy_field += calculate_spatial_beam_power(X, Y, ue_positions[i], ris_pos)

    # Update heatmap visualization (Normalized for display)
    beam_field.set_array(total_energy_field / max_users)

    # Update UE markers
    scat.set_offsets(ue_positions)

    return [beam_field, scat]

# 2. Animation Engine Setup
ani = FuncAnimation(fig, update_field_simulation, frames=150, interval=60, blit=True)
ax.set_xlim(0, 10); ax.set_ylim(0, 10)
# RIS Node Visualization
ax.scatter(ris_pos[0], ris_pos[1], color='gold', s=400, marker='s', zorder=4,
           label='6G RIS Node', edgecolors='black')

ax.set_title("Advanced 6G Field Simulation: Spatial Multi-User Beamforming")
ax.set_xlabel("Spatial Width (m)")
ax.set_ylabel("Spatial Depth (m)")
ax.legend(loc='upper right')
plt.close()

# Exporting High-Resolution Field Animation
HTML(ani.to_html5_video())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 1. Environment & Proactive Handover Configuration
fig, ax = plt.subplots(figsize=(10, 8))
# The RIS is mounted precisely on the glass storefront/entrance
ris_pos = np.array([5, 2])
door_threshold_y = 2

num_users = 4
# Initialize User Equipments (UEs) starting from the external street zone
ue_positions = np.random.uniform(1, 9, (num_users, 2))
ue_positions[:, 1] = np.random.uniform(-2, 1, num_users)
velocities = np.array([[0, 0.08] for _ in range(num_users)])

# Visualization Elements
scat = ax.scatter([], [], s=200, zorder=5, edgecolors='white', label='Mobile UEs')
beams = [ax.plot([], [], lw=2.5)[0] for i in range(num_users)]

# Environment Boundary Delineation
ax.axhline(door_threshold_y, color='black', lw=2) # Storefront Glass interface
ax.fill_between([0, 10], 2, 10, color='skyblue', alpha=0.1, label='Indoor Domain (High-Gain)')
ax.fill_between([0, 10], -4, 2, color='grey', alpha=0.1, label='Outdoor Domain (Proactive Sensing)')

def update_handover_simulation(frame):
    """
    Simulates the AI-driven handover between Outdoor Sensing and Indoor Communication.
    The system maintains 'Service Continuity' as users cross the physical threshold.
    """
    global ue_positions
    ue_positions += velocities

    for i in range(num_users):
        # 1. OUTDOOR STATE: Proactive Predictive Beamforming
        # The RIS projects a directional beam to the street to 'acquire' the user
        if ue_positions[i, 1] < door_threshold_y:
            beams[i].set_data([ris_pos[0], ue_positions[i, 0]], [ris_pos[1], ue_positions[i, 1]])
            beams[i].set_color('orange') # Orange: Proactive acquisition mode
            beams[i].set_linestyle('--')
            beams[i].set_alpha(0.6)

        # 2. INDOOR STATE: Instantaneous Ultra-Reliable Link (URLLC)
        # Upon entry, the AI switches to a high-intensity, stable data link
        else:
            beams[i].set_data([ris_pos[0], ue_positions[i, 0]], [ris_pos[1], ue_positions[i, 1]])
            beams[i].set_color('lime') # Lime: Full 6G Capacity established
            beams[i].set_linestyle('-')
            beams[i].set_alpha(1.0)

    # Spatial Rendering: Color coding UEs based on their current domain
    scat.set_offsets(ue_positions)
    ue_colors = ['dodgerblue' if p[1] >= door_threshold_y else 'crimson' for p in ue_positions]
    scat.set_color(ue_colors)

    return [scat] + beams

# 2. Animation Engine Setup
ani = FuncAnimation(fig, update_handover_simulation, frames=120, interval=50, blit=True)

# Visualize the RIS as a Smart Transparent Surface (Window-Mounted)
ax.scatter(ris_pos[0], ris_pos[1], color='gold', s=400, marker='s',
           label='Window-Mounted RIS Node', zorder=6, edgecolors='black')

ax.set_xlim(0, 10); ax.set_ylim(-4, 10)
ax.set_title("6G Seamless Handover: Transitioning from Street Sensing to Indoor Link")
ax.set_xlabel("Lateral Position (m)")
ax.set_ylabel("Depth / Entrance Progress (m)")
ax.legend(loc='upper right')
ax.grid(alpha=0.2, linestyle=':')
plt.close()

# Exporting the dynamic handover sequence
HTML(ani.to_html5_video())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 1. Physical & Array Configuration (6G mmWave Parameters)
fig, ax = plt.subplots(figsize=(12, 9))
ris_pos = np.array([5, 0.5])
num_elements = 16
frequency = 28e9  # 28 GHz
lambda_w = 3e8 / frequency
spacing = lambda_w / 2

# Grid for Wave Propagation Simulation
res = 150
X, Y = np.meshgrid(np.linspace(0, 10, res), np.linspace(0, 10, res))

# 2. Hybrid Physics-Protocol Engine
def get_hybrid_field(target_ue_pos, elements, space, wav):
    """
    Calculates the actual electromagnetic interference pattern (Beamforming)
    based on constructive and destructive interference.
    """
    dx_u = target_ue_pos[0] - ris_pos[0]
    dy_u = target_ue_pos[1] - ris_pos[1]
    theta_d = np.arctan2(dy_u, dx_u)

    # AI-Calculated Phase Shifts to steer the beam
    phases = -2 * np.pi * (np.arange(elements) * space / wav) * np.cos(theta_d)

    complex_field = np.zeros(X.shape, dtype=complex)
    for i in range(elements):
        # Physical offset for each antenna element
        element_x = ris_pos[0] + (i - elements/2) * space
        r = np.sqrt((X - element_x)**2 + (Y - ris_pos[1])**2)
        # Superposition of waves
        complex_field += (1/r) * np.exp(1j * (phases[i] + 2 * np.pi * r / wav))

    power = 20 * np.log10(np.abs(complex_field))
    return power - np.max(power) # Normalized dB Map

# Visual Elements
field_plot = ax.imshow(np.zeros((res, res)), extent=[0, 10, 0, 10],
                       origin='lower', cmap='turbo', vmin=-25, vmax=0, alpha=0.8)
ue_scat = ax.scatter([], [], s=250, edgecolors='black', zorder=5)
status_text = ax.text(0.5, 9.2, "", fontsize=14, fontweight='bold',
                      bbox=dict(facecolor='white', alpha=0.8))

def update(frame):
    # Path: Complex Elliptical Mobility
    angle = np.radians(frame)
    curr_ue = np.array([5 + 3.5*np.cos(angle), 5.5 + 2.5*np.sin(angle*1.5)])

    # Physics Layer: Calculate Beam Pattern
    field_data = get_hybrid_field(curr_ue, num_elements, spacing, lambda_w)
    field_plot.set_array(field_data)

    # Logic Layer: Quality of Service (QoS) based on Physical Gain
    # If the user is in a 'Side Lobe' or distance is too high, signal drops
    ue_x_idx = int(curr_ue[0] * (res/10))
    ue_y_idx = int(curr_ue[1] * (res/10))
    # Clip indices to stay within bounds
    ue_x_idx = np.clip(ue_x_idx, 0, res-1)
    ue_y_idx = np.clip(ue_y_idx, 0, res-1)

    received_gain = field_data[ue_y_idx, ue_x_idx]

    # 6G State Machine
    if received_gain > -3:
        status = "6G Link: ULTRA-RELIABLE (URLLC)"
        ue_color = 'lime'
    elif received_gain > -12:
        status = "6G Link: STABLE (eMBB)"
        ue_color = 'yellow'
    else:
        status = "6G Link: BEAM TRAINING / SEARCHING..."
        ue_color = 'red'

    ue_scat.set_offsets(curr_ue)
    ue_scat.set_color(ue_color)
    status_text.set_text(f"{status} | Gain: {received_gain:.1f} dB")

    return [field_plot, ue_scat, status_text]

# 3. Execution
ani = FuncAnimation(fig, update, frames=np.arange(0, 360, 2), interval=60, blit=True)
ax.scatter(ris_pos[0], ris_pos[1], color='gold', s=500, marker='s', label='Active RIS Array', zorder=6)
ax.set_title("Hybrid 6G RIS: Physical Wave Interference & Protocol Logic")
ax.set_xlabel("Width (m)"); ax.set_ylabel("Depth (m)")
plt.legend(loc='lower right'); plt.close()
HTML(ani.to_html5_video())